### ISSUE TITLE
Script ends with error

### ISSUE THREAD

**Issue by fm4d** [vedant/markov-chain-generator#1]
Hello, it looks like your script does not work. I am getting this error:

``` python
Traceback (most recent call last):
 File "markov.py", line 92, in <module>
    text = m.generate_text(60)
  File "markov.py", line 38, in generate_text
    seed = random.randint(0, self.num_words-self.order)
  File "/usr/lib/python2.7/random.py", line 241, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python2.7/random.py", line 217, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,-3, -3) 
```

**Comment by vedant** [comment]
``` python
ValueError: empty range for randrange() (0,-3, -3) 
```

means that `self.numwords - self.order < 0`. Specifically, in this case, that `self.numwords - self.order = -4`.  In other words, `self.numwords` is zero. That's because Google has changed the structure of SERP for Google Scholar, which means the function `scrape_from_google` has to be modified.

I haven't been maintaining this, but it's a simple matter to inspect the source of a results page on Google scholar and write a new regex to find titles.

**Comment by fm4d** [comment]
I kinda expected that. Well I just wanted to inform you :)
